/** Generated by scenario-recordings.test.ts from authoritative room batches. */
export const REPLAY_RECORDINGS = [
  "effects-lab-own-chain",
  "effects-lab-nested",
  "effects-lab-prod-attack-stack",
  "effects-lab-prod-security-removed",
  "effects-lab-prod-titan-cascade",
  "effects-lab-prod-ghost-execute-security",
  "arena-bt24-silphymon-dna",
  "phase-pacing-bot-raising-move",
  "keyword-pacing-recovery-many",
  "keyword-pacing-draw-many",
] as const;
