import { EffectDuration, EffectTiming } from "@aegis/shared";
import type { CardSource } from "../../engine/effects/CardSource.js";
import type { Effect } from "../../engine/effects/Effect.js";
import type { EffectModule } from "../../engine/effects/EffectModule.js";
import { staticModifier } from "../../engine/effects/builders.js";
import { registerCard } from "../../engine/effects/registry.js";
const cardId = "ST6-11";
const module: EffectModule = { cardId, effectsForTiming(timing: EffectTiming, source: CardSource): Effect[] { if (timing !== EffectTiming.None) return []; return [staticModifier({ source, effectKey: `${cardId}/trash-dp`, description: "[Your Turn] With 5 or more cards in trash, this Digimon gets +2000 DP.", isInherited: true, when: (ctx) => source.isOwnersTurn() && ctx.game.player(source.ownerSeat).trash.length >= 5, resolve: async (ctx) => { const self = source.permanent(); if (self) ctx.fx.modifyDP(self.permanentId, 2000, EffectDuration.UntilEachTurnEnd); } })]; } };
registerCard(module);
export default module;
