import { EffectDuration, EffectTiming } from "@aegis/shared";
import type { CardSource } from "../../engine/effects/CardSource.js";
import type { Effect } from "../../engine/effects/Effect.js";
import type { EffectModule } from "../../engine/effects/EffectModule.js";
import { staticModifier } from "../../engine/effects/builders.js";
import { registerCard } from "../../engine/effects/registry.js";
const cardId = "ST5-01";
const module: EffectModule = { cardId, effectsForTiming(timing: EffectTiming, source: CardSource): Effect[] { if (timing !== EffectTiming.None) return []; return [staticModifier({ source, effectKey: `${cardId}/blocker-dp`, description: "[Your Turn] While this Digimon has Blocker, it gets +1000 DP.", isInherited: true, when: (ctx) => { const self = source.permanent(); return source.isOwnersTurn() && self !== undefined && (ctx.game.hasKeyword?.(self.permanentId, "Blocker") ?? false); }, resolve: async (ctx) => { const self = source.permanent(); if (self) ctx.fx.modifyDP(self.permanentId, 1000, EffectDuration.UntilEachTurnEnd, { continuous: true }); } })]; } };
registerCard(module);
export default module;
