import { EffectDuration, EffectTiming } from "@aegis/shared";
import type { CardSource } from "../../engine/effects/CardSource.js";
import type { Effect } from "../../engine/effects/Effect.js";
import type { EffectModule } from "../../engine/effects/EffectModule.js";
import { staticModifier, whenAttacking } from "../../engine/effects/builders.js";
import { registerCard } from "../../engine/effects/registry.js";
const cardId = "ST4-08";
const module: EffectModule = { cardId, effectsForTiming(timing: EffectTiming, source: CardSource): Effect[] { if (timing === EffectTiming.None) return [staticModifier({ source, effectKey: `${cardId}/blocker`, description: "Blocker.", resolve: async (ctx) => { const self = source.permanent(); if (self) ctx.fx.grantKeyword(self.permanentId, "Blocker", EffectDuration.Permanent); } })]; if (timing === EffectTiming.OnUseAttack) return [whenAttacking({ source, effectKey: `${cardId}/attack-memory`, description: "[When Attacking] Lose 2 memory.", resolve: async (ctx) => { ctx.fx.gainMemoryForSeat(source.ownerSeat, -2); } })]; return []; } };
registerCard(module);
export default module;
