// Generated by tools/diagnostics/render-original-audio.mjs; do not edit offsets.
export const AUDIO_BANK_URL = "/audio/aegis-cues-v2.wav?v=03cbd5129ced";
export const MUSIC_URL = "/audio/aegis-music-v3.wav?v=69cbe499a72a";
export const AUDIO_CUES: Record<string, { offset: number; duration: number }> = {
  select: {
    offset: 0,
    duration: 0.09927083333333334,
  },
  nav: {
    offset: 0.12427083333333333,
    duration: 0.15429166666666666,
  },
  confirm: {
    offset: 0.3035625,
    duration: 0.16802083333333334,
  },
  attack: {
    offset: 0.4965833333333333,
    duration: 0.254625,
  },
  error: {
    offset: 0.7762083333333333,
    duration: 0.20427083333333335,
  },
  success: {
    offset: 1.0054791666666667,
    duration: 0.18966666666666668,
  },
  attackDeclare: {
    offset: 1.2201458333333333,
    duration: 0.7822916666666667,
  },
  securityHit: {
    offset: 2.0274375,
    duration: 0.323875,
  },
  turnChange: {
    offset: 2.3763125,
    duration: 0.29302083333333334,
  },
  endTurn: {
    offset: 2.6943333333333332,
    duration: 0.34427083333333336,
  },
  hatch: {
    offset: 3.0636041666666665,
    duration: 0.27466666666666667,
  },
  effectFocus: {
    offset: 3.3632708333333334,
    duration: 0.163375,
  },
  effectActivate: {
    offset: 3.551645833333333,
    duration: 0.2191875,
  },
  handTrash: {
    offset: 3.7958333333333334,
    duration: 0.5219583333333333,
  },
  sourceTrash: {
    offset: 4.342791666666667,
    duration: 0.343875,
  },
  deDigivolve: {
    offset: 4.711666666666667,
    duration: 0.6469583333333333,
  },
  delete: {
    offset: 5.383625,
    duration: 0.7736458333333334,
  },
  move: {
    offset: 6.182270833333333,
    duration: 0.5982708333333333,
  },
  draw: {
    offset: 6.805541666666667,
    duration: 0.139375,
  },
  shuffle: {
    offset: 6.969916666666666,
    duration: 0.569375,
  },
  reveal: {
    offset: 7.564291666666667,
    duration: 0.2191875,
  },
  impact: {
    offset: 7.808479166666666,
    duration: 0.254625,
  },
  buff: {
    offset: 8.088104166666668,
    duration: 0.15833333333333333,
  },
  debuff: {
    offset: 8.2714375,
    duration: 0.5219583333333333,
  },
  freeze: {
    offset: 8.818395833333334,
    duration: 0.288875,
  },
  recover: {
    offset: 9.132270833333333,
    duration: 0.5982708333333333,
  },
  group: {
    offset: 9.755541666666666,
    duration: 0.6049583333333334,
  },
  win: {
    offset: 10.3855,
    duration: 0.42302083333333335,
  },
  lose: {
    offset: 10.833520833333333,
    duration: 0.6849583333333333,
  },
  "cardPlay-0-plain": {
    offset: 11.543479166666666,
    duration: 0.18966666666666668,
  },
  "cardPlay-0-assembly": {
    offset: 11.758145833333334,
    duration: 0.23833333333333334,
  },
  "cardPlay-1-plain": {
    offset: 12.021479166666667,
    duration: 0.18966666666666668,
  },
  "cardPlay-1-assembly": {
    offset: 12.236145833333333,
    duration: 0.23833333333333334,
  },
  "cardPlay-2-plain": {
    offset: 12.499479166666667,
    duration: 0.18966666666666668,
  },
  "cardPlay-2-assembly": {
    offset: 12.714145833333333,
    duration: 0.23833333333333334,
  },
  "cardPlay-3-plain": {
    offset: 12.977479166666667,
    duration: 0.18966666666666668,
  },
  "cardPlay-3-assembly": {
    offset: 13.192145833333333,
    duration: 0.23833333333333334,
  },
  "cardPlay-4-plain": {
    offset: 13.455479166666667,
    duration: 0.23427083333333334,
  },
  "cardPlay-4-assembly": {
    offset: 13.71475,
    duration: 0.23833333333333334,
  },
  "cardPlay-5-plain": {
    offset: 13.978083333333334,
    duration: 0.23427083333333334,
  },
  "cardPlay-5-assembly": {
    offset: 14.237354166666666,
    duration: 0.23833333333333334,
  },
  "cardPlay-6-plain": {
    offset: 14.5006875,
    duration: 0.23427083333333334,
  },
  "cardPlay-6-assembly": {
    offset: 14.759958333333334,
    duration: 0.23833333333333334,
  },
  "cardPlay-7-plain": {
    offset: 15.023291666666667,
    duration: 0.23427083333333334,
  },
  "cardPlay-7-assembly": {
    offset: 15.2825625,
    duration: 0.23833333333333334,
  },
  "cardPlay-8-plain": {
    offset: 15.545895833333333,
    duration: 0.23427083333333334,
  },
  "cardPlay-8-assembly": {
    offset: 15.805166666666667,
    duration: 0.23833333333333334,
  },
  "cardPlay-9-plain": {
    offset: 16.0685,
    duration: 0.254625,
  },
  "cardPlay-9-assembly": {
    offset: 16.348125,
    duration: 0.254625,
  },
  "cardPlay-10-plain": {
    offset: 16.62775,
    duration: 0.254625,
  },
  "cardPlay-10-assembly": {
    offset: 16.907375,
    duration: 0.254625,
  },
  "cardPlay-11-plain": {
    offset: 17.187,
    duration: 0.254625,
  },
  "cardPlay-11-assembly": {
    offset: 17.466625,
    duration: 0.254625,
  },
  "cardPlay-12-plain": {
    offset: 17.74625,
    duration: 0.254625,
  },
  "cardPlay-12-assembly": {
    offset: 18.025875,
    duration: 0.254625,
  },
  "cardPlay-13-plain": {
    offset: 18.3055,
    duration: 0.5249583333333333,
  },
  "cardPlay-13-assembly": {
    offset: 18.855458333333335,
    duration: 0.5249583333333333,
  },
  "cardPlay-14-plain": {
    offset: 19.405416666666667,
    duration: 0.5249583333333333,
  },
  "cardPlay-14-assembly": {
    offset: 19.955375,
    duration: 0.5249583333333333,
  },
  "cardPlay-15-plain": {
    offset: 20.505333333333333,
    duration: 0.5249583333333333,
  },
  "cardPlay-15-assembly": {
    offset: 21.055291666666665,
    duration: 0.5249583333333333,
  },
  "digivolve-1-2": {
    offset: 21.60525,
    duration: 0.32566666666666666,
  },
  "digivolve-1-3": {
    offset: 21.955916666666667,
    duration: 0.39366666666666666,
  },
  "digivolve-1-4": {
    offset: 22.374583333333334,
    duration: 0.526625,
  },
  "digivolve-1-5": {
    offset: 22.926208333333335,
    duration: 0.526625,
  },
  "digivolve-1-6": {
    offset: 23.477833333333333,
    duration: 0.7969583333333333,
  },
  "digivolve-1-7": {
    offset: 24.299791666666668,
    duration: 0.7969583333333333,
  },
  "digivolve-2-2": {
    offset: 25.12175,
    duration: 0.33766666666666667,
  },
  "digivolve-2-3": {
    offset: 25.484416666666668,
    duration: 0.33766666666666667,
  },
  "digivolve-2-4": {
    offset: 25.847083333333334,
    duration: 0.476625,
  },
  "digivolve-2-5": {
    offset: 26.348708333333335,
    duration: 0.550625,
  },
  "digivolve-2-6": {
    offset: 26.924333333333333,
    duration: 0.8209583333333333,
  },
  "digivolve-2-7": {
    offset: 27.770291666666665,
    duration: 0.8209583333333333,
  },
  "digivolve-3-2": {
    offset: 28.61625,
    duration: 0.3496666666666667,
  },
  "digivolve-3-3": {
    offset: 28.990916666666667,
    duration: 0.3496666666666667,
  },
  "digivolve-3-4": {
    offset: 29.365583333333333,
    duration: 0.414625,
  },
  "digivolve-3-5": {
    offset: 29.805208333333333,
    duration: 0.494625,
  },
  "digivolve-3-6": {
    offset: 30.324833333333334,
    duration: 0.8449583333333334,
  },
  "digivolve-3-7": {
    offset: 31.194791666666667,
    duration: 0.8449583333333334,
  },
  "digivolve-4-2": {
    offset: 32.06475,
    duration: 0.3616666666666667,
  },
  "digivolve-4-3": {
    offset: 32.45141666666667,
    duration: 0.3616666666666667,
  },
  "digivolve-4-4": {
    offset: 32.83808333333333,
    duration: 0.426625,
  },
  "digivolve-4-5": {
    offset: 33.28970833333333,
    duration: 0.512625,
  },
  "digivolve-4-6": {
    offset: 33.827333333333335,
    duration: 0.8689583333333334,
  },
  "digivolve-4-7": {
    offset: 34.721291666666666,
    duration: 0.8689583333333334,
  },
  "digivolve-5-2": {
    offset: 35.61525,
    duration: 0.37366666666666665,
  },
  "digivolve-5-3": {
    offset: 36.01391666666667,
    duration: 0.37366666666666665,
  },
  "digivolve-5-4": {
    offset: 36.41258333333333,
    duration: 0.438625,
  },
  "digivolve-5-5": {
    offset: 36.87620833333333,
    duration: 0.530625,
  },
  "digivolve-5-6": {
    offset: 37.43183333333333,
    duration: 0.8929583333333333,
  },
  "digivolve-5-7": {
    offset: 38.34979166666667,
    duration: 0.8929583333333333,
  },
  "digivolve-6-2": {
    offset: 39.26775,
    duration: 0.38566666666666666,
  },
  "digivolve-6-3": {
    offset: 39.678416666666664,
    duration: 0.38566666666666666,
  },
  "digivolve-6-4": {
    offset: 40.089083333333335,
    duration: 0.450625,
  },
  "digivolve-6-5": {
    offset: 40.564708333333336,
    duration: 0.548625,
  },
  "digivolve-6-6": {
    offset: 41.138333333333335,
    duration: 0.9169583333333333,
  },
  "digivolve-6-7": {
    offset: 42.08029166666667,
    duration: 0.9169583333333333,
  },
  "digivolve-7-2": {
    offset: 43.02225,
    duration: 0.39766666666666667,
  },
  "digivolve-7-3": {
    offset: 43.444916666666664,
    duration: 0.39766666666666667,
  },
  "digivolve-7-4": {
    offset: 43.867583333333336,
    duration: 0.462625,
  },
  "digivolve-7-5": {
    offset: 44.35520833333333,
    duration: 0.566625,
  },
  "digivolve-7-6": {
    offset: 44.94683333333333,
    duration: 0.9409583333333333,
  },
  "digivolve-7-7": {
    offset: 45.912791666666664,
    duration: 0.9409583333333333,
  },
};
