// Generated by tools/diagnostics/render-original-audio.mjs; do not edit offsets.
export const AUDIO_BANK_URL = "/audio/aegis-cues-v2.wav?v=0e94616b3750";
export const MUSIC_URL = "/audio/aegis-music-v2.wav?v=0ac715d3d9c4";
export const AUDIO_CUES: Record<string, { offset: number; duration: number }> = {
  select: {
    offset: 0,
    duration: 0.12,
  },
  nav: {
    offset: 0.145,
    duration: 0.11,
  },
  confirm: {
    offset: 0.28,
    duration: 0.485,
  },
  attack: {
    offset: 0.79,
    duration: 0.357,
  },
  error: {
    offset: 1.172,
    duration: 0.265,
  },
  success: {
    offset: 1.462,
    duration: 0.585,
  },
  attackDeclare: {
    offset: 2.072,
    duration: 0.365,
  },
  securityHit: {
    offset: 2.462,
    duration: 0.455,
  },
  turnChange: {
    offset: 2.942,
    duration: 0.645,
  },
  endTurn: {
    offset: 3.612,
    duration: 0.555,
  },
  hatch: {
    offset: 4.192,
    duration: 0.645,
  },
  effectFocus: {
    offset: 4.862,
    duration: 0.36,
  },
  effectActivate: {
    offset: 5.247,
    duration: 0.51,
  },
  handTrash: {
    offset: 5.782,
    duration: 0.365,
  },
  sourceTrash: {
    offset: 6.172,
    duration: 0.255,
  },
  deDigivolve: {
    offset: 6.452,
    duration: 0.65,
  },
  delete: {
    offset: 7.127,
    duration: 0.645,
  },
  move: {
    offset: 7.797,
    duration: 0.305,
  },
  draw: {
    offset: 8.127,
    duration: 0.205,
  },
  shuffle: {
    offset: 8.357,
    duration: 0.45,
  },
  reveal: {
    offset: 8.832,
    duration: 0.455,
  },
  impact: {
    offset: 9.312,
    duration: 0.357,
  },
  buff: {
    offset: 9.694,
    duration: 0.565,
  },
  debuff: {
    offset: 10.284,
    duration: 0.575,
  },
  freeze: {
    offset: 10.884,
    duration: 0.485,
  },
  recover: {
    offset: 11.394,
    duration: 0.665,
  },
  group: {
    offset: 12.084,
    duration: 0.385,
  },
  win: {
    offset: 12.494,
    duration: 1.195,
  },
  lose: {
    offset: 13.714,
    duration: 0.865,
  },
  "cardPlay-0-plain": {
    offset: 14.604,
    duration: 0.357,
  },
  "cardPlay-0-assembly": {
    offset: 14.986,
    duration: 0.705,
  },
  "cardPlay-1-plain": {
    offset: 15.716,
    duration: 0.357,
  },
  "cardPlay-1-assembly": {
    offset: 16.098,
    duration: 0.705,
  },
  "cardPlay-2-plain": {
    offset: 16.828,
    duration: 0.357,
  },
  "cardPlay-2-assembly": {
    offset: 17.21,
    duration: 0.705,
  },
  "cardPlay-3-plain": {
    offset: 17.94,
    duration: 0.357,
  },
  "cardPlay-3-assembly": {
    offset: 18.322,
    duration: 0.705,
  },
  "cardPlay-4-plain": {
    offset: 19.052,
    duration: 0.3586666666666667,
  },
  "cardPlay-4-assembly": {
    offset: 19.435666666666666,
    duration: 0.705,
  },
  "cardPlay-5-plain": {
    offset: 20.165666666666667,
    duration: 0.37333333333333335,
  },
  "cardPlay-5-assembly": {
    offset: 20.564,
    duration: 0.705,
  },
  "cardPlay-6-plain": {
    offset: 21.294,
    duration: 0.388,
  },
  "cardPlay-6-assembly": {
    offset: 21.707,
    duration: 0.705,
  },
  "cardPlay-7-plain": {
    offset: 22.437,
    duration: 0.4026666666666667,
  },
  "cardPlay-7-assembly": {
    offset: 22.86466666666667,
    duration: 0.705,
  },
  "cardPlay-8-plain": {
    offset: 23.594666666666665,
    duration: 0.41733333333333333,
  },
  "cardPlay-8-assembly": {
    offset: 24.037,
    duration: 0.705,
  },
  "cardPlay-9-plain": {
    offset: 24.767,
    duration: 0.432,
  },
  "cardPlay-9-assembly": {
    offset: 25.224,
    duration: 0.705,
  },
  "cardPlay-10-plain": {
    offset: 25.954,
    duration: 0.44666666666666666,
  },
  "cardPlay-10-assembly": {
    offset: 26.425666666666668,
    duration: 0.705,
  },
  "cardPlay-11-plain": {
    offset: 27.155666666666665,
    duration: 0.4613333333333333,
  },
  "cardPlay-11-assembly": {
    offset: 27.642,
    duration: 0.705,
  },
  "cardPlay-12-plain": {
    offset: 28.372,
    duration: 0.476,
  },
  "cardPlay-12-assembly": {
    offset: 28.873,
    duration: 0.705,
  },
  "cardPlay-13-plain": {
    offset: 29.603,
    duration: 0.49066666666666664,
  },
  "cardPlay-13-assembly": {
    offset: 30.118666666666666,
    duration: 0.705,
  },
  "cardPlay-14-plain": {
    offset: 30.848666666666666,
    duration: 0.5053333333333333,
  },
  "cardPlay-14-assembly": {
    offset: 31.379,
    duration: 0.705,
  },
  "cardPlay-15-plain": {
    offset: 32.109,
    duration: 0.52,
  },
  "cardPlay-15-assembly": {
    offset: 32.654,
    duration: 0.705,
  },
  "digivolve-1-2": {
    offset: 33.384,
    duration: 0.93,
  },
  "digivolve-1-3": {
    offset: 34.339,
    duration: 0.99,
  },
  "digivolve-1-4": {
    offset: 35.354,
    duration: 1.05,
  },
  "digivolve-1-5": {
    offset: 36.429,
    duration: 1.11,
  },
  "digivolve-1-6": {
    offset: 37.564,
    duration: 1.17,
  },
  "digivolve-1-7": {
    offset: 38.759,
    duration: 1.23,
  },
  "digivolve-2-2": {
    offset: 40.014,
    duration: 0.93,
  },
  "digivolve-2-3": {
    offset: 40.969,
    duration: 0.955,
  },
  "digivolve-2-4": {
    offset: 41.949,
    duration: 1.015,
  },
  "digivolve-2-5": {
    offset: 42.989,
    duration: 1.075,
  },
  "digivolve-2-6": {
    offset: 44.089,
    duration: 1.135,
  },
  "digivolve-2-7": {
    offset: 45.249,
    duration: 1.195,
  },
  "digivolve-3-2": {
    offset: 46.469,
    duration: 0.93,
  },
  "digivolve-3-3": {
    offset: 47.424,
    duration: 0.955,
  },
  "digivolve-3-4": {
    offset: 48.404,
    duration: 0.98,
  },
  "digivolve-3-5": {
    offset: 49.409,
    duration: 1.04,
  },
  "digivolve-3-6": {
    offset: 50.474,
    duration: 1.1,
  },
  "digivolve-3-7": {
    offset: 51.599,
    duration: 1.16,
  },
  "digivolve-4-2": {
    offset: 52.784,
    duration: 0.93,
  },
  "digivolve-4-3": {
    offset: 53.739,
    duration: 0.955,
  },
  "digivolve-4-4": {
    offset: 54.719,
    duration: 0.98,
  },
  "digivolve-4-5": {
    offset: 55.724,
    duration: 1.005,
  },
  "digivolve-4-6": {
    offset: 56.754,
    duration: 1.065,
  },
  "digivolve-4-7": {
    offset: 57.844,
    duration: 1.125,
  },
  "digivolve-5-2": {
    offset: 58.994,
    duration: 0.93,
  },
  "digivolve-5-3": {
    offset: 59.949,
    duration: 0.955,
  },
  "digivolve-5-4": {
    offset: 60.929,
    duration: 0.98,
  },
  "digivolve-5-5": {
    offset: 61.934,
    duration: 1.005,
  },
  "digivolve-5-6": {
    offset: 62.964,
    duration: 1.03,
  },
  "digivolve-5-7": {
    offset: 64.019,
    duration: 1.09,
  },
  "digivolve-6-2": {
    offset: 65.134,
    duration: 0.93,
  },
  "digivolve-6-3": {
    offset: 66.089,
    duration: 0.955,
  },
  "digivolve-6-4": {
    offset: 67.069,
    duration: 0.98,
  },
  "digivolve-6-5": {
    offset: 68.074,
    duration: 1.005,
  },
  "digivolve-6-6": {
    offset: 69.104,
    duration: 1.03,
  },
  "digivolve-6-7": {
    offset: 70.159,
    duration: 1.055,
  },
  "digivolve-7-2": {
    offset: 71.239,
    duration: 0.93,
  },
  "digivolve-7-3": {
    offset: 72.194,
    duration: 0.955,
  },
  "digivolve-7-4": {
    offset: 73.174,
    duration: 0.98,
  },
  "digivolve-7-5": {
    offset: 74.179,
    duration: 1.005,
  },
  "digivolve-7-6": {
    offset: 75.209,
    duration: 1.03,
  },
  "digivolve-7-7": {
    offset: 76.264,
    duration: 1.055,
  },
};
