// Generated by tools/diagnostics/render-original-audio.mjs; do not edit offsets.
export const AUDIO_BANK_URL = "/audio/aegis-cues-v2.wav?v=1f37ddc39a09";
export const MUSIC_URL = "/audio/aegis-music-v3.wav?v=69cbe499a72a";
export const AUDIO_CUES: Record<string, { offset: number; duration: number }> = {
  select: {
    offset: 0,
    duration: 0.09927083333333334,
  },
  nav: {
    offset: 0.12427083333333333,
    duration: 0.15429166666666666,
  },
  confirm: {
    offset: 0.3035625,
    duration: 0.16802083333333334,
  },
  attack: {
    offset: 0.4965833333333333,
    duration: 0.254625,
  },
  error: {
    offset: 0.7762083333333333,
    duration: 0.20427083333333335,
  },
  success: {
    offset: 1.0054791666666667,
    duration: 0.18966666666666668,
  },
  attackDeclare: {
    offset: 1.2201458333333333,
    duration: 0.7822916666666667,
  },
  securityHit: {
    offset: 2.0274375,
    duration: 0.323875,
  },
  turnChange: {
    offset: 2.3763125,
    duration: 0.29302083333333334,
  },
  endTurn: {
    offset: 2.6943333333333332,
    duration: 0.34427083333333336,
  },
  hatch: {
    offset: 3.0636041666666665,
    duration: 0.27466666666666667,
  },
  effectFocus: {
    offset: 3.3632708333333334,
    duration: 0.163375,
  },
  effectActivate: {
    offset: 3.551645833333333,
    duration: 0.2191875,
  },
  handTrash: {
    offset: 3.7958333333333334,
    duration: 0.5219583333333333,
  },
  sourceTrash: {
    offset: 4.342791666666667,
    duration: 0.343875,
  },
  deDigivolve: {
    offset: 4.711666666666667,
    duration: 0.6469583333333333,
  },
  delete: {
    offset: 5.383625,
    duration: 0.7736458333333334,
  },
  block: {
    offset: 6.182270833333333,
    duration: 0.348875,
  },
  protect: {
    offset: 6.556145833333333,
    duration: 0.6482708333333334,
  },
  prompt: {
    offset: 7.229416666666666,
    duration: 0.18302083333333333,
  },
  timerTick: {
    offset: 7.4374375,
    duration: 0.09302083333333333,
  },
  phase: {
    offset: 7.555458333333333,
    duration: 0.15302083333333333,
  },
  securityDeal: {
    offset: 7.733479166666666,
    duration: 0.18966666666666668,
  },
  optionUse: {
    offset: 7.948145833333333,
    duration: 0.2942708333333333,
  },
  move: {
    offset: 8.267416666666668,
    duration: 0.5982708333333333,
  },
  draw: {
    offset: 8.8906875,
    duration: 0.139375,
  },
  shuffle: {
    offset: 9.0550625,
    duration: 0.569375,
  },
  reveal: {
    offset: 9.6494375,
    duration: 0.2191875,
  },
  impact: {
    offset: 9.893625,
    duration: 0.254625,
  },
  buff: {
    offset: 10.17325,
    duration: 0.15833333333333333,
  },
  debuff: {
    offset: 10.356583333333333,
    duration: 0.5219583333333333,
  },
  freeze: {
    offset: 10.903541666666667,
    duration: 0.288875,
  },
  recover: {
    offset: 11.217416666666667,
    duration: 0.5982708333333333,
  },
  group: {
    offset: 11.8406875,
    duration: 0.6049583333333334,
  },
  win: {
    offset: 12.470645833333334,
    duration: 0.42302083333333335,
  },
  lose: {
    offset: 12.918666666666667,
    duration: 0.6849583333333333,
  },
  "memory-1": {
    offset: 13.628625,
    duration: 0.09302083333333333,
  },
  "memory-2": {
    offset: 13.746645833333334,
    duration: 0.14102083333333335,
  },
  "memory-3": {
    offset: 13.912666666666667,
    duration: 0.18902083333333333,
  },
  "memory-4": {
    offset: 14.1266875,
    duration: 0.23702083333333332,
  },
  "memory-5": {
    offset: 14.388708333333334,
    duration: 0.28502083333333333,
  },
  "memory-6": {
    offset: 14.698729166666666,
    duration: 0.3330208333333333,
  },
  "cardPlay-0-plain": {
    offset: 15.05675,
    duration: 0.18966666666666668,
  },
  "cardPlay-0-assembly": {
    offset: 15.271416666666667,
    duration: 0.23833333333333334,
  },
  "cardPlay-1-plain": {
    offset: 15.53475,
    duration: 0.18966666666666668,
  },
  "cardPlay-1-assembly": {
    offset: 15.749416666666667,
    duration: 0.23833333333333334,
  },
  "cardPlay-2-plain": {
    offset: 16.01275,
    duration: 0.18966666666666668,
  },
  "cardPlay-2-assembly": {
    offset: 16.227416666666667,
    duration: 0.23833333333333334,
  },
  "cardPlay-3-plain": {
    offset: 16.49075,
    duration: 0.18966666666666668,
  },
  "cardPlay-3-assembly": {
    offset: 16.705416666666668,
    duration: 0.23833333333333334,
  },
  "cardPlay-4-plain": {
    offset: 16.96875,
    duration: 0.23427083333333334,
  },
  "cardPlay-4-assembly": {
    offset: 17.228020833333332,
    duration: 0.23833333333333334,
  },
  "cardPlay-5-plain": {
    offset: 17.491354166666667,
    duration: 0.23427083333333334,
  },
  "cardPlay-5-assembly": {
    offset: 17.750625,
    duration: 0.23833333333333334,
  },
  "cardPlay-6-plain": {
    offset: 18.013958333333335,
    duration: 0.23427083333333334,
  },
  "cardPlay-6-assembly": {
    offset: 18.273229166666667,
    duration: 0.23833333333333334,
  },
  "cardPlay-7-plain": {
    offset: 18.5365625,
    duration: 0.23427083333333334,
  },
  "cardPlay-7-assembly": {
    offset: 18.795833333333334,
    duration: 0.23833333333333334,
  },
  "cardPlay-8-plain": {
    offset: 19.059166666666666,
    duration: 0.23427083333333334,
  },
  "cardPlay-8-assembly": {
    offset: 19.3184375,
    duration: 0.23833333333333334,
  },
  "cardPlay-9-plain": {
    offset: 19.581770833333334,
    duration: 0.254625,
  },
  "cardPlay-9-assembly": {
    offset: 19.861395833333333,
    duration: 0.254625,
  },
  "cardPlay-10-plain": {
    offset: 20.141020833333332,
    duration: 0.254625,
  },
  "cardPlay-10-assembly": {
    offset: 20.42064583333333,
    duration: 0.254625,
  },
  "cardPlay-11-plain": {
    offset: 20.700270833333335,
    duration: 0.254625,
  },
  "cardPlay-11-assembly": {
    offset: 20.979895833333334,
    duration: 0.254625,
  },
  "cardPlay-12-plain": {
    offset: 21.259520833333333,
    duration: 0.254625,
  },
  "cardPlay-12-assembly": {
    offset: 21.539145833333333,
    duration: 0.254625,
  },
  "cardPlay-13-plain": {
    offset: 21.818770833333332,
    duration: 0.5249583333333333,
  },
  "cardPlay-13-assembly": {
    offset: 22.368729166666668,
    duration: 0.5249583333333333,
  },
  "cardPlay-14-plain": {
    offset: 22.9186875,
    duration: 0.5249583333333333,
  },
  "cardPlay-14-assembly": {
    offset: 23.468645833333333,
    duration: 0.5249583333333333,
  },
  "cardPlay-15-plain": {
    offset: 24.018604166666666,
    duration: 0.5249583333333333,
  },
  "cardPlay-15-assembly": {
    offset: 24.5685625,
    duration: 0.5249583333333333,
  },
  "digivolve-1-2": {
    offset: 25.118520833333335,
    duration: 0.988,
  },
  "digivolve-1-3": {
    offset: 26.131520833333333,
    duration: 1.273,
  },
  "digivolve-1-4": {
    offset: 27.429520833333335,
    duration: 1.273,
  },
  "digivolve-1-5": {
    offset: 28.727520833333333,
    duration: 1.558,
  },
  "digivolve-1-6": {
    offset: 30.31052083333333,
    duration: 1.843,
  },
  "digivolve-1-7": {
    offset: 32.17852083333333,
    duration: 2.128,
  },
  "digivolve-2-2": {
    offset: 34.331520833333336,
    duration: 0.988,
  },
  "digivolve-2-3": {
    offset: 35.344520833333334,
    duration: 0.988,
  },
  "digivolve-2-4": {
    offset: 36.35752083333333,
    duration: 1.273,
  },
  "digivolve-2-5": {
    offset: 37.655520833333334,
    duration: 1.558,
  },
  "digivolve-2-6": {
    offset: 39.23852083333333,
    duration: 1.843,
  },
  "digivolve-2-7": {
    offset: 41.106520833333335,
    duration: 2.128,
  },
  "digivolve-3-2": {
    offset: 43.25952083333333,
    duration: 0.988,
  },
  "digivolve-3-3": {
    offset: 44.27252083333333,
    duration: 0.988,
  },
  "digivolve-3-4": {
    offset: 45.28552083333334,
    duration: 0.988,
  },
  "digivolve-3-5": {
    offset: 46.298520833333335,
    duration: 1.558,
  },
  "digivolve-3-6": {
    offset: 47.88152083333333,
    duration: 1.843,
  },
  "digivolve-3-7": {
    offset: 49.749520833333335,
    duration: 2.128,
  },
  "digivolve-4-2": {
    offset: 51.902520833333334,
    duration: 0.988,
  },
  "digivolve-4-3": {
    offset: 52.91552083333333,
    duration: 0.988,
  },
  "digivolve-4-4": {
    offset: 53.92852083333333,
    duration: 0.988,
  },
  "digivolve-4-5": {
    offset: 54.941520833333335,
    duration: 1.273,
  },
  "digivolve-4-6": {
    offset: 56.23952083333333,
    duration: 1.843,
  },
  "digivolve-4-7": {
    offset: 58.10752083333333,
    duration: 2.128,
  },
  "digivolve-5-2": {
    offset: 60.26052083333333,
    duration: 0.988,
  },
  "digivolve-5-3": {
    offset: 61.273520833333336,
    duration: 0.988,
  },
  "digivolve-5-4": {
    offset: 62.286520833333334,
    duration: 0.988,
  },
  "digivolve-5-5": {
    offset: 63.29952083333333,
    duration: 1.273,
  },
  "digivolve-5-6": {
    offset: 64.59752083333333,
    duration: 1.558,
  },
  "digivolve-5-7": {
    offset: 66.18052083333333,
    duration: 2.128,
  },
  "digivolve-6-2": {
    offset: 68.33352083333334,
    duration: 0.988,
  },
  "digivolve-6-3": {
    offset: 69.34652083333333,
    duration: 0.988,
  },
  "digivolve-6-4": {
    offset: 70.35952083333333,
    duration: 0.988,
  },
  "digivolve-6-5": {
    offset: 71.37252083333334,
    duration: 1.273,
  },
  "digivolve-6-6": {
    offset: 72.67052083333333,
    duration: 1.558,
  },
  "digivolve-6-7": {
    offset: 74.25352083333334,
    duration: 1.843,
  },
  "digivolve-7-2": {
    offset: 76.12152083333334,
    duration: 0.988,
  },
  "digivolve-7-3": {
    offset: 77.13452083333334,
    duration: 0.988,
  },
  "digivolve-7-4": {
    offset: 78.14752083333333,
    duration: 0.988,
  },
  "digivolve-7-5": {
    offset: 79.16052083333334,
    duration: 1.273,
  },
  "digivolve-7-6": {
    offset: 80.45852083333334,
    duration: 1.558,
  },
  "digivolve-7-7": {
    offset: 82.04152083333334,
    duration: 1.843,
  },
};
