export const DIGIMON_WORLD_AVATARS = [
  { id: "phoenixmon", name: "Phoenixmon", sourceFile: "Hououmon_card_dw.png" },
  { id: "herculeskabuterimon", name: "HerculesKabuterimon", sourceFile: "Heraklekabuterimon_card_dw.png" },
  { id: "megaseadramon", name: "MegaSeadramon", sourceFile: "Megaseadramon_card_dw.png" },
  { id: "shogungekomon", name: "ShogunGekomon", sourceFile: "Tonosamagekomon_card_dw.png" },
  { id: "myotismon", name: "Myotismon", sourceFile: "Vamdemon_card_dw.png" },
  { id: "metalgreymon-virus", name: "MetalGreymon (Virus)", sourceFile: "Metalgreymon_virus_card_dw.png" },
  { id: "mamemon", name: "Mamemon", sourceFile: "Mamemon_card_dw.png" },
  { id: "monzaemon", name: "Monzaemon", sourceFile: "Monzaemon_card_dw.png" },
  { id: "skullgreymon", name: "SkullGreymon", sourceFile: "Skullgreymon_card_dw.png" },
  { id: "metalmamemon", name: "MetalMamemon", sourceFile: "Metalmamemon_card_dw.png" },
  { id: "vademon", name: "Vademon", sourceFile: "Vademon_card_dw.png" },
  { id: "andromon", name: "Andromon", sourceFile: "Andromon_card_dw.png" },
  { id: "giromon", name: "Giromon", sourceFile: "Giromon_card_dw.png" },
  { id: "etemon", name: "Etemon", sourceFile: "Etemon_card_dw.png" },
  { id: "megadramon", name: "Megadramon", sourceFile: "Megadramon_card_dw.png" },
  { id: "piximon", name: "Piximon", sourceFile: "Piccolomon_card_dw.png" },
  { id: "digitamamon", name: "Digitamamon", sourceFile: "Digitamamon_card_dw.png" },
  { id: "gekomon", name: "Gekomon", sourceFile: "Gekomon_card_dw.png" },
  { id: "warumonzaemon", name: "WaruMonzaemon", sourceFile: "Warumonzaemon_card_dw.png" },
  { id: "jijimon", name: "Jijimon", sourceFile: "Jijimon_card_dw.png" },
  { id: "kingsukamon", name: "KingSukamon", sourceFile: "Greatkingscumon_card_dw.png" },
  { id: "cherrymon", name: "Cherrymon", sourceFile: "Jyureimon_card_dw.png" },
  { id: "guardromon", name: "Guardromon", sourceFile: "Guardromon_card_dw.png" },
  { id: "hagurumon", name: "Hagurumon", sourceFile: "Hagurumon_card_dw.png" },
  { id: "brachiomon", name: "Brachiomon", sourceFile: "Brachimon_card_dw.png" },
  { id: "greymon", name: "Greymon", sourceFile: "Greymon_card_dw.png" },
  { id: "devimon", name: "Devimon", sourceFile: "Devimon_card_dw.png" },
  { id: "airdramon", name: "Airdramon", sourceFile: "Airdramon_card_dw.png" },
  { id: "tyrannomon", name: "Tyrannomon", sourceFile: "Tyranomon_card_dw.png" },
  { id: "meramon", name: "Meramon", sourceFile: "Meramon_card_dw.png" },
  { id: "seadramon", name: "Seadramon", sourceFile: "Seadramon_card_dw.png" },
  { id: "kabuterimon", name: "Kabuterimon", sourceFile: "Kabuterimon_card_dw.png" },
  { id: "angemon", name: "Angemon", sourceFile: "Angemon_card_dw.png" },
  { id: "birdramon", name: "Birdramon", sourceFile: "Birdramon_card_dw.png" },
  { id: "garurumon", name: "Garurumon", sourceFile: "Garurumon_card_dw.png" },
  { id: "frigimon", name: "Frigimon", sourceFile: "Yukidarumon_card_dw.png" },
  { id: "whamon", name: "Whamon", sourceFile: "Whamon_card_dw.png" },
  { id: "unimon", name: "Unimon", sourceFile: "Unimon_card_dw.png" },
  { id: "ogremon", name: "Ogremon", sourceFile: "Orgemon_card_dw.png" },
  { id: "shellmon", name: "Shellmon", sourceFile: "Shellmon_card_dw.png" },
  { id: "centarumon", name: "Centarumon", sourceFile: "Centalmon_card_dw.png" },
  { id: "bakemon", name: "Bakemon", sourceFile: "Bakemon_card_dw.png" },
  { id: "drimogemon", name: "Drimogemon", sourceFile: "Drimogemon_card_dw.png" },
  { id: "monochromon", name: "Monochromon", sourceFile: "Monochromon_card_dw.png" },
  { id: "leomon", name: "Leomon", sourceFile: "Leomon_card_dw.png" },
  { id: "coelamon", name: "Coelamon", sourceFile: "Coelamon_card_dw.png" },
  { id: "kokatorimon", name: "Kokatorimon", sourceFile: "Cockatrimon_card_dw.png" },
  { id: "kuwagamon", name: "Kuwagamon", sourceFile: "Kuwagamon_card_dw.png" },
  { id: "mojyamon", name: "Mojyamon", sourceFile: "Mojyamon_card_dw.png" },
  { id: "ninjamon", name: "Ninjamon", sourceFile: "Igamon_card_dw.png" },
  { id: "penguinmon", name: "Penguinmon", sourceFile: "Penmon_card_dw.png" },
  { id: "otamamon", name: "Otamamon", sourceFile: "Otamamon_card_dw.png" },
  { id: "tentomon", name: "Tentomon", sourceFile: "Tentomon_card_dw.png" },
  { id: "yanmamon", name: "Yanmamon", sourceFile: "Yanmamon_card_dw.png" },
  { id: "gotsumon", name: "Gotsumon", sourceFile: "Gottsumon_card_dw.png" },
  { id: "flarerizamon", name: "Flarerizamon", sourceFile: "Flarelizarmon_card_dw.png" },
  { id: "toyagumon", name: "ToyAgumon", sourceFile: "Toyagumon_card_dw.png" },
  { id: "demimeramon", name: "DemiMeramon", sourceFile: "Petimeramon_card_dw.png" },
  { id: "tankmon", name: "Tankmon", sourceFile: "Tankmon_card_dw.png" },
  { id: "goburimon", name: "Goburimon", sourceFile: "Goburimon_card_dw.png" },
  { id: "numemon", name: "Numemon", sourceFile: "Numemon_card_dw.png" },
  { id: "vegiemon", name: "Vegiemon", sourceFile: "Vegimon_card_dw.png" },
  { id: "sukamon", name: "Sukamon", sourceFile: "Scumon_card_dw.png" },
  { id: "nanimon", name: "Nanimon", sourceFile: "Nanimon_card_dw.png" },
  { id: "machinedramon", name: "Machinedramon", sourceFile: "Mugendramon_card_dw.png" },
] as const;

export type DigimonWorldAvatarId = (typeof DIGIMON_WORLD_AVATARS)[number]["id"];

const DIGIMON_WORLD_AVATAR_IDS = new Set<string>(DIGIMON_WORLD_AVATARS.map(({ id }) => id));

export function isDigimonWorldAvatarId(value: unknown): value is DigimonWorldAvatarId {
  return typeof value === "string" && DIGIMON_WORLD_AVATAR_IDS.has(value);
}
