import { CardColor } from "../schema/enums.js";
import { defineMetaDeck, type DeckEntry, type FamousDeck } from "./types.js";

const entries = (rows: ReadonlyArray<readonly [string, number, string]>): DeckEntry[] =>
  rows.map(([cardId, count]) => ({ cardId, count }));

const SOURCE_URL = "https://world.digimoncard.com/products/pack/ex-13/";

/**
 * EX13 Chivalrous XIII: one deck per Royal Knight.
 *
 * The product page publishes full recipes only for its Adventure, Imperialdramon and
 * Mamemon decks (stored in `data/ex13.json`). For the thirteen Royal Knights it publishes a
 * one-paragraph deck guide each. These lists follow those guides, built from the EX13 cards
 * and each knight's most recent support, so every knight is playable ahead of the set's
 * 2026-10-02 release. Nothing here is a tournament result.
 */
export const EX13_ROYAL_KNIGHTS_DECKS: readonly FamousDeck[] = Object.freeze([
  defineMetaDeck({
    deckId: "ex13-omnimon-royal-knights",
    revision: 1,
    name: "EX13 Omnimon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "Omnimon",
    colors: [CardColor.Red, CardColor.Blue, CardColor.White, CardColor.Black],
    source: "Built from the Omnimon deck guide on the EX13 product page. Nokia Shiramine drops Agumon and Gabumon into play, the Cyber Sleuth Greymon and Garurumon lines feed WarGreymon and MetalGarurumon, and the pair DNA digivolve for free into an Omnimon that deletes by digivolution-card count.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["BT22-008", 4, "Agumon Lv.3"],
      ["BT22-017", 4, "Gabumon Lv.3"],
      ["EX13-017", 2, "Veemon Lv.3"],
      ["BT23-008", 4, "Greymon Lv.4"],
      ["BT23-018", 4, "Garurumon Lv.4"],
      ["BT22-012", 3, "RizeGreymon Lv.5"],
      ["BT23-056", 3, "WereGarurumon Lv.5"],
      ["BT22-013", 4, "WarGreymon Lv.6"],
      ["BT22-026", 4, "MetalGarurumon Lv.6"],
      ["EX13-016", 4, "Omnimon Lv.7"],
      ["BT22-015", 2, "Omnimon Lv.7"],
      ["BT23-054", 2, "Magnamon Lv.4"],
      ["EX13-067", 4, "Nokia Shiramine Tamer"],
      ["BT22-084", 3, "Nokia Shiramine Tamer"],
      ["BT22-094", 3, "Yuugo Kamishiro Tamer"],
    ]),
    eggDeck: entries([
      ["BT22-005", 4, "Tsumemon"],
    ]),
  }),
  defineMetaDeck({
    deckId: "ex13-alphamon-royal-knights",
    revision: 1,
    name: "EX13 Alphamon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "Alphamon",
    colors: [CardColor.Black, CardColor.Yellow, CardColor.Red],
    source: "Built from the Alphamon deck guide on the EX13 product page. Raptordramon and Grademon chain digivolutions while attacking, Kota Domoto fuels the hand, and Alphamon's end-of-turn play sneaks an extra Chronicle attacker in for 6 less.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["EX13-049", 4, "Dorumon Lv.3"],
      ["BT20-048", 4, "Dorumon Lv.3"],
      ["BT20-010", 2, "Ryudamon Lv.3"],
      ["EX13-055", 4, "Raptordramon Lv.4"],
      ["BT20-051", 3, "Raptordramon Lv.4"],
      ["BT20-012", 1, "Ginryumon Lv.4"],
      ["EX13-057", 4, "Grademon Lv.5"],
      ["BT20-053", 3, "Grademon Lv.5"],
      ["BT20-015", 1, "Hisyaryumon Lv.5"],
      ["EX13-060", 4, "Alphamon Lv.6"],
      ["BT20-056", 2, "Alphamon Lv.6"],
      ["BT20-018", 2, "Ouryumon Lv.6"],
      ["BT20-060", 3, "Alphamon: Ouryuken Lv.7"],
      ["EX13-072", 4, "Kota Domoto Tamer"],
      ["BT20-087", 3, "Kota Domoto & Yuji Musya Tamer"],
      ["BT20-095", 3, "Fellowship of Hope's Keepers Option"],
      ["P-204", 3, "Release of the Sealed Knight! Option"],
    ]),
    eggDeck: entries([
      ["EX13-006", 4, "Dorimon"],
      ["P-176", 1, "Dorimon"],
    ]),
  }),
  defineMetaDeck({
    deckId: "ex13-ulforceveedramon-royal-knights",
    revision: 1,
    name: "EX13 UlforceVeedramon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "UlforceVeedramon",
    colors: [CardColor.Blue, CardColor.Yellow, CardColor.White, CardColor.Red, CardColor.Black, CardColor.Green],
    source: "Built from the UlforceVeedramon deck guide on the EX13 product page. AeroVeedramon plays Rina Shinomiya for free, Rina draws and digivolves on every unsuspend, and UlforceVeedramon bounces the opponent's thinnest stacks while shrugging off removal.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["EX13-017", 4, "Veemon Lv.3"],
      ["BT22-019", 4, "Veemon Lv.3"],
      ["P-248", 2, "Veemon Lv.3"],
      ["EX13-019", 4, "Veedramon Lv.4"],
      ["BT22-022", 4, "Veedramon Lv.4"],
      ["EX13-022", 4, "AeroVeedramon Lv.5"],
      ["BT22-023", 3, "AeroVeedramon Lv.5"],
      ["EX13-023", 4, "UlforceVeedramon Lv.6"],
      ["BT22-025", 3, "UlforceVeedramon Lv.6"],
      ["BT12-029", 1, "UlforceVeedramon (X Antibody) Lv.6"],
      ["EX13-069", 4, "Rina Shinomiya Tamer"],
      ["BT22-085", 3, "Rina Shinomiya Tamer"],
      ["BT11-112", 2, "Rina Shinomiya Tamer"],
      ["BT23-054", 2, "Magnamon Lv.4"],
      ["EX13-020", 2, "Magnamon Lv.4"],
      ["EX13-076", 2, "Imperialdramon: Paladin Mode Lv.7"],
      ["BT22-094", 2, "Yuugo Kamishiro Tamer"],
    ]),
    eggDeck: entries([
      ["EX13-002", 4, "DemiVeemon"],
    ]),
  }),
  defineMetaDeck({
    deckId: "ex13-magnamon-royal-knights",
    revision: 1,
    name: "EX13 Magnamon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "Magnamon",
    colors: [CardColor.Blue, CardColor.Yellow, CardColor.Black, CardColor.White, CardColor.Red, CardColor.Green],
    source: "Built from the Magnamon deck guide on the EX13 product page. Every Veemon feeds Magnamon's Assembly; Magnamon grows with the colours in the trashes, drains the opposing DP, and unsuspends a Royal Knight at the end of each turn.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["EX13-017", 4, "Veemon Lv.3"],
      ["BT22-019", 4, "Veemon Lv.3"],
      ["P-248", 4, "Veemon Lv.3"],
      ["BT12-021", 2, "Veemon Lv.3"],
      ["P-117", 2, "Veemon Lv.3"],
      ["EX13-020", 4, "Magnamon Lv.4"],
      ["BT23-054", 4, "Magnamon Lv.4"],
      ["BT21-036", 3, "Magnamon Lv.4"],
      ["BT8-038", 2, "Magnamon Lv.4"],
      ["BT16-102", 3, "Magnamon (X Antibody) Lv.6"],
      ["BT9-044", 2, "Magnamon (X Antibody) Lv.6"],
      ["EX13-023", 2, "UlforceVeedramon Lv.6"],
      ["EX13-076", 2, "Imperialdramon: Paladin Mode Lv.7"],
      ["EX13-069", 3, "Rina Shinomiya Tamer"],
      ["P-124", 3, "Davis Motomiya Tamer"],
      ["BT12-090", 2, "Davis Motomiya Tamer"],
      ["EX13-022", 2, "AeroVeedramon Lv.5"],
      ["BT22-023", 2, "AeroVeedramon Lv.5"],
    ]),
    eggDeck: entries([
      ["EX13-002", 4, "DemiVeemon"],
      ["P-188", 1, "DemiVeemon"],
    ]),
  }),
  defineMetaDeck({
    deckId: "ex13-lordknightmon-royal-knights",
    revision: 1,
    name: "EX13 LordKnightmon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "LordKnightmon",
    colors: [CardColor.Purple, CardColor.Black],
    source: "Built from the LordKnightmon deck guide on the EX13 product page. Kotemon and Gladimon keep Knightmon cards flowing under Rie Kishibe, who digivolves into LordKnightmon for 3 once three Knightmon cards sit under her; LordKnightmon hands every Knightmon Alliance and Piercing.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["EX13-048", 4, "Kotemon Lv.3"],
      ["BT18-058", 4, "Kotemon Lv.3"],
      ["BT19-055", 2, "Monitamon Lv.3"],
      ["EX13-052", 4, "Gladimon Lv.4"],
      ["EX10-026", 3, "SkullKnightmon Lv.4"],
      ["EX10-027", 3, "DeadlyAxemon Lv.4"],
      ["BT18-062", 2, "Gladimon Lv.4"],
      ["EX13-058", 4, "Knightmon Lv.5"],
      ["EX10-031", 3, "DarkKnightmon Lv.5"],
      ["BT19-063", 3, "DarkKnightmon Lv.5"],
      ["EX13-064", 4, "LordKnightmon Lv.6"],
      ["BT18-083", 2, "LordKnightmon Lv.6"],
      ["BT19-073", 2, "LordKnightmon (X Antibody) Lv.6"],
      ["AD1-018", 1, "LordKnightmon Lv.6"],
      ["EX13-074", 4, "Rie Kishibe Tamer"],
      ["BT22-090", 2, "Rie Kishibe Tamer"],
      ["BT18-099", 3, "Fist of Athena Option"],
    ]),
    eggDeck: entries([
      ["BT16-005", 4, "Dorimon"],
    ]),
  }),
  defineMetaDeck({
    deckId: "ex13-gallantmon-royal-knights",
    revision: 1,
    name: "EX13 Gallantmon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "Gallantmon",
    colors: [CardColor.Red, CardColor.Purple],
    source: "Built from the Gallantmon deck guide on the EX13 product page. Gigimon digivolves for cheap when Takato is played, WarGrowlmon's Engage brings Takato back, and Gallantmon deletes 12000 DP Digimon while staying on the field by deleting a smaller one.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["EX13-007", 4, "Guilmon Lv.3"],
      ["BT19-007", 4, "Guilmon Lv.3"],
      ["BT21-064", 2, "Guilmon Lv.3"],
      ["EX13-010", 4, "Growlmon Lv.4"],
      ["BT19-009", 3, "Growlmon Lv.4"],
      ["BT17-010", 2, "Growlmon Lv.4"],
      ["EX13-013", 4, "WarGrowlmon Lv.5"],
      ["AD1-003", 3, "WarGrowlmon Lv.5"],
      ["BT19-011", 2, "WarGrowlmon Lv.5"],
      ["EX13-015", 4, "Gallantmon Lv.6"],
      ["AD1-008", 2, "Gallantmon Lv.6"],
      ["BT19-015", 2, "Gallantmon Lv.6"],
      ["BT17-018", 2, "Gallantmon: Crimson Mode Lv.7"],
      ["EX13-068", 4, "Takato Matsuki Tamer"],
      ["BT19-080", 3, "Takato Matsuki Tamer"],
      ["BT21-089", 2, "Takato Matsuki Tamer"],
      ["BT17-096", 3, "Crimson Savior Option"],
    ]),
    eggDeck: entries([
      ["EX13-001", 4, "Gigimon"],
      ["BT17-001", 1, "Gigimon"],
    ]),
  }),
  defineMetaDeck({
    deckId: "ex13-dynasmon-royal-knights",
    revision: 1,
    name: "EX13 Dynasmon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "Dynasmon",
    colors: [CardColor.Yellow, CardColor.Red, CardColor.Purple, CardColor.Black],
    source: "Built from the Dynasmon deck guide on the EX13 product page. Candlemon and Mistymon trash the deck's own security to shrink the opponent's board, DemiMeramon digivolves into a Witchelny card on the attack, and Dynasmon swings with +10000 DP once security is low.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["EX13-025", 4, "Candlemon Lv.3"],
      ["BT18-030", 4, "Candlemon Lv.3"],
      ["BT19-029", 2, "Tapirmon Lv.3"],
      ["EX13-029", 4, "FlameWizardmon Lv.4"],
      ["BT18-036", 3, "Wizardmon Lv.4"],
      ["BT19-036", 2, "Wizardmon (X Antibody) Lv.4"],
      ["BT15-036", 3, "Wizardmon Lv.4"],
      ["EX13-033", 4, "Mistymon Lv.5"],
      ["EX13-034", 3, "Wisemon Lv.5"],
      ["BT18-039", 2, "Mistymon Lv.5"],
      ["BT19-039", 2, "SkullBaluchimon Lv.5"],
      ["BT6-035", 2, "Baluchimon Lv.4"],
      ["EX13-037", 4, "Dynasmon Lv.6"],
      ["BT18-040", 3, "Dynasmon Lv.6"],
      ["BT19-042", 2, "Dynasmon (X Antibody) Lv.6"],
      ["BT19-041", 2, "Dynasmon Lv.6"],
      ["BT23-035", 1, "Dynasmon Lv.6"],
      ["BT18-098", 3, "Dragon's Roar Option"],
    ]),
    eggDeck: entries([
      ["EX13-004", 4, "DemiMeramon"],
      ["BT18-001", 1, "DemiMeramon"],
    ]),
  }),
  defineMetaDeck({
    deckId: "ex13-craniamon-royal-knights",
    revision: 1,
    name: "EX13 Craniamon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "Craniamon",
    colors: [CardColor.Black],
    source: "Built from the Craniamon deck guide on the EX13 product page. Guardromon keeps every other Blocker on the field, Giromon plays more Blockers whenever a Digimon suspends, and Craniamon wipes the opponent's cheapest Digimon each time it blocks.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["EX13-047", 4, "Gotsumon Lv.3"],
      ["BT13-061", 4, "Gotsumon Lv.3"],
      ["BT20-047", 3, "Solarmon Lv.3"],
      ["P-144", 1, "Gotsumon (X Antibody) Lv.3"],
      ["EX13-050", 2, "Bokomon Lv.3"],
      ["BT15-055", 2, "Hagurumon Lv.3"],
      ["EX13-051", 4, "Guardromon Lv.4"],
      ["BT15-061", 3, "Guardromon Lv.4"],
      ["EX12-054", 2, "Guardromon Lv.4"],
      ["BT16-057", 2, "Mekanorimon Lv.4"],
      ["EX1-047", 2, "Guardromon Lv.4"],
      ["EX13-056", 4, "Giromon Lv.5"],
      ["EX2-034", 2, "Andromon Lv.5"],
      ["BT13-071", 2, "Giromon Lv.5"],
      ["BT20-054", 2, "Bulbmon Lv.5"],
      ["EX13-062", 4, "Craniamon Lv.6"],
      ["BT23-058", 2, "Craniamon Lv.6"],
      ["BT13-077", 2, "Craniamon Lv.6"],
      ["BT3-075", 1, "Craniamon Lv.6"],
      ["ST15-13", 2, "HiAndromon Lv.6"],
    ]),
    eggDeck: entries([
      ["BT16-005", 4, "Dorimon"],
      ["ST5-01", 1, "Kapurimon"],
    ]),
  }),
  defineMetaDeck({
    deckId: "ex13-kentaurosmon-royal-knights",
    revision: 1,
    name: "EX13 Kentaurosmon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "Kentaurosmon",
    colors: [CardColor.Yellow, CardColor.Blue, CardColor.White],
    source: "Built from the Kentaurosmon deck guide on the EX13 product page. Kudamon stacks cards under Richard Sampson, Sampson digivolves it straight into Kentaurosmon, Chirinmon keeps the stack safe, and Kentaurosmon's Counter turns Digimon into security cards mid-attack.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["EX13-026", 4, "Kudamon Lv.3"],
      ["BT13-034", 4, "Kudamon Lv.3"],
      ["EX5-028", 2, "Kudamon Lv.3"],
      ["EX13-030", 4, "Reppamon Lv.4"],
      ["BT22-034", 3, "Reppamon Lv.4"],
      ["BT13-038", 2, "Reppamon Lv.4"],
      ["EX13-032", 4, "Chirinmon Lv.5"],
      ["BT22-037", 3, "Chirinmon Lv.5"],
      ["EX5-031", 2, "Chirinmon Lv.5"],
      ["EX13-036", 4, "Kentaurosmon Lv.6"],
      ["BT22-041", 3, "Kentaurosmon Lv.6"],
      ["BT13-046", 1, "Kentaurosmon Lv.6"],
      ["EX13-071", 4, "Richard Sampson Tamer"],
      ["BT13-098", 3, "Richard Sampson Tamer"],
      ["ST24-13", 3, "Marcus Damon & Thomas H. Norstein Tamer"],
      ["P-235", 2, "Digital Accident Tactics Squad Option"],
      ["ST24-15", 2, "DNA Charge Option"],
    ]),
    eggDeck: entries([
      ["EX13-003", 4, "Kyaromon"],
      ["BT13-003", 1, "Kyaromon"],
    ]),
  }),
  defineMetaDeck({
    deckId: "ex13-leopardmon-royal-knights",
    revision: 1,
    name: "EX13 Leopardmon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "Leopardmon",
    colors: [CardColor.Green, CardColor.Yellow, CardColor.Red],
    source: "Built from the Leopardmon deck guide on the EX13 product page. Salamon searches the beasts, Bastemon plays them for free while attacking, Mikemon suspends the opponent's board, and Leopardmon plays or uses a beast for 4 less plus 1 per suspended Digimon.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["EX13-038", 4, "Salamon Lv.3"],
      ["BT13-048", 4, "Salamon Lv.3"],
      ["EX13-040", 4, "Mikemon Lv.4"],
      ["BT13-051", 3, "Mikemon Lv.4"],
      ["BT12-036", 3, "Mikemon Lv.4"],
      ["EX12-042", 3, "Gatomon Lv.4"],
      ["EX5-030", 3, "Liamon Lv.4"],
      ["EX13-042", 4, "Bastemon Lv.5"],
      ["P-093", 4, "Bastemon Lv.5"],
      ["EX13-043", 4, "Leopardmon Lv.6"],
      ["BT13-058", 3, "Leopardmon: Leopard Mode Lv.6"],
      ["BT22-052", 3, "Leopardmon Lv.6"],
      ["EX5-043", 2, "Leopardmon (X Antibody) Lv.6"],
      ["BT13-056", 2, "Leopardmon Lv.6"],
      ["BT23-078", 4, "Gorou Matayoshi Tamer"],
    ]),
    eggDeck: entries([
      ["BT23-002", 4, "Yokomon"],
    ]),
  }),
  defineMetaDeck({
    deckId: "ex13-examon-royal-knights",
    revision: 1,
    name: "EX13 Examon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "Examon",
    colors: [CardColor.Green, CardColor.Red, CardColor.Blue],
    source: "Built from the Examon deck guide on the EX13 product page. Bebydomon and Coredramon cheat Dracomon-text cards into play, Wingdramon and Groundramon count as Slayerdramon and Breakdramon for DNA digivolution, and Examon attacks the moment it DNA digivolves.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["EX13-008", 4, "Dracomon Lv.3"],
      ["BT20-007", 4, "Dracomon Lv.3"],
      ["BT21-046", 2, "Dracomon (X Antibody) Lv.3"],
      ["EX13-018", 4, "Coredramon Lv.4"],
      ["EX13-039", 4, "Coredramon Lv.4"],
      ["BT20-023", 1, "Coredramon Lv.4"],
      ["BT20-040", 1, "Coredramon Lv.4"],
      ["EX13-021", 4, "Wingdramon Lv.5"],
      ["EX13-041", 4, "Groundramon Lv.5"],
      ["BT20-025", 1, "Wingdramon Lv.5"],
      ["BT20-042", 1, "Groundramon Lv.5"],
      ["EX13-024", 3, "Slayerdramon Lv.6"],
      ["EX13-044", 3, "Breakdramon Lv.6"],
      ["BT20-027", 1, "Slayerdramon Lv.6"],
      ["BT20-044", 1, "Breakdramon Lv.6"],
      ["EX13-045", 4, "Examon Lv.7"],
      ["BT20-045", 3, "Examon Lv.7"],
      ["BT21-052", 1, "Examon (X Antibody) Lv.7"],
      ["BT20-093", 4, "Unleash the Dragon Gene Option"],
    ]),
    eggDeck: entries([
      ["EX13-005", 4, "Bebydomon"],
      ["BT20-002", 1, "Bebydomon"],
    ]),
  }),
  defineMetaDeck({
    deckId: "ex13-gankoomon-jesmon-royal-knights",
    revision: 1,
    name: "EX13 Gankoomon & Jesmon",
    block: "EX13",
    anchorProduct: "EX13",
    archetype: "Gankoomon & Jesmon",
    colors: [CardColor.Red, CardColor.White, CardColor.Black, CardColor.Yellow],
    source: "Built from the Gankoomon & Jesmon deck guide on the EX13 product page. Huckmon searches the sisters, SaviorHuckmon plays the Awakened Sistermon for 3 less, Jesmon deletes on every play and brings out Atho, René & Por, and Gankoomon adds Hinukamuy with full effect immunity.",
    sourceUrl: SOURCE_URL,
    mainDeck: entries([
      ["EX13-009", 4, "Huckmon Lv.3"],
      ["BT23-006", 4, "Huckmon Lv.3"],
      ["BT20-008", 2, "Huckmon Lv.3"],
      ["EX13-065", 3, "Sistermon Blanc (Awakened) Lv.3"],
      ["BT23-076", 2, "Sistermon Blanc Lv.3"],
      ["EX13-011", 4, "BaoHuckmon Lv.4"],
      ["BT20-013", 2, "BaoHuckmon Lv.4"],
      ["EX13-066", 3, "Sistermon Noir (Awakened) Lv.4"],
      ["BT23-077", 2, "Sistermon Ciel Lv.4"],
      ["EX13-012", 4, "SaviorHuckmon Lv.5"],
      ["BT20-014", 2, "SaviorHuckmon Lv.5"],
      ["EX13-014", 4, "Jesmon Lv.6"],
      ["BT23-013", 2, "Jesmon Lv.6"],
      ["EX13-061", 3, "Gankoomon Lv.6"],
      ["BT23-057", 1, "Gankoomon Lv.6"],
      ["BT20-021", 2, "Jesmon GX Lv.7"],
      ["EX13-075", 4, "Mon Tamer"],
      ["BT23-099", 2, "The Sistermon Sisters Training Gym Option"],
    ]),
    eggDeck: entries([
      ["BT20-001", 4, "DemiVeemon"],
    ]),
  }),
]);
